# -*- coding: utf-8 -*-
"""scoliosispinn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ki2V0EUMiTyJeXXNfbVdMiCI3QWhsZ1N
"""

!pip install -q deepxde

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import deepxde as dde
import seaborn as sns
import re

from deepxde.backend import torch
from scipy.integrate import odeint

sns.set_theme(style="whitegrid")

"""# Model

$$
\begin{aligned}
\frac{dS}{dt} &= - \alpha  S \\
\frac{dI^L}{dt} &= q \alpha S + \rho R - \tau^L I^H \\
\frac{dI^H}{dt} &= (1-q) \alpha S - \tau^H I^H \\
\frac{dT}{dt} &= \tau^L I^L + \tau^H I^H - \lambda T \\
\frac{dR}{dt} &= p \lambda T - \rho R\\
\frac{dC}{dt} &= (1-p) \lambda T \\
\end{aligned}
$$
"""

from scipy.special import expit
import tensorflow as tf

noise_levels = [0.01, 0.05, 0.10, 0.20]
n_trials = 10
predicted_parameters = {}
parameters_history_by_noise = {}

N = 1e6
a = 0.045
l = 0.1
p = 0.9
r = 0.01
q = 0.85
t_L = 0.2
t_H = 0.8
parameters_real = [a, l, p, r, q, t_L, t_H]
parameter_names = ["alpha", "lambda", "p", "r", "q", "tau_L", "tau_H"]

t = np.arange(0, 365, 7)[:, np.newaxis]

def siitrc_model(t, y, a, l, p, r, q, t_L, t_H):

    def func(y, t):
        S, I_L, I_H, T, R, C = y
        dS = -a * S
        dI_L = q * a * S + r * R - t_L * I_L
        dI_H = (1-q) * a * S - t_H * I_H
        dT = t_L * I_L + t_H * I_H - l * T
        dR = p * l * T - r * R
        dC = (1-p) * l * T
        return [dS, dI_L, dI_H, dT, dR, dC]

    S_0 = N
    I_H_0 = 0
    I_L_0 = 0
    T_0 = 0
    R_0 = 0
    C_0 = 0
    y0 = [S_0, I_L_0, I_H_0, T_0, R_0, C_0]
    return odeint(func, y0, t)

y = siitrc_model(np.ravel(t), N, a, l, p, r, q, t_L, t_H)

import tensorflow as tf

def dinn(data_t, data_y, N, noise_level, variable_filename="variables.dat"):
    init_val = -2.197
    a_raw = dde.Variable(init_val)
    l_raw = dde.Variable(init_val)
    p_raw = dde.Variable(init_val)
    r_raw = dde.Variable(init_val)
    q_raw = dde.Variable(init_val)
    t_L_raw = dde.Variable(init_val)
    t_H_raw = dde.Variable(init_val)

    variable_list = [a_raw, l_raw, p_raw, r_raw, q_raw, t_L_raw, t_H_raw]

    def ODE(t, y_pred):
        a = tf.math.sigmoid(a_raw)
        l = tf.math.sigmoid(l_raw)
        p = tf.math.sigmoid(p_raw)
        r = tf.math.sigmoid(r_raw)
        q = tf.math.sigmoid(q_raw)
        t_L = tf.math.sigmoid(t_L_raw)
        t_H = tf.math.sigmoid(t_H_raw)

        S_pred = y_pred[:, 0:1]
        I_L_pred = y_pred[:, 1:2]
        I_H_pred = y_pred[:, 2:3]
        T_pred = y_pred[:, 3:4]
        R_pred = y_pred[:, 4:5]
        C_pred = y_pred[:, 5:6]

        dS_pred_t = dde.grad.jacobian(y_pred, t, i=0)
        dI_L_pred_t = dde.grad.jacobian(y_pred, t, i=1)
        dI_H_pred_t = dde.grad.jacobian(y_pred, t, i=2)
        dT_pred_t = dde.grad.jacobian(y_pred, t, i=3)
        dR_pred_t = dde.grad.jacobian(y_pred, t, i=4)
        dC_pred_t = dde.grad.jacobian(y_pred, t, i=5)

        return [
            dS_pred_t - (-a * S_pred),
            dI_L_pred_t - (q * a * S_pred + r * R_pred - t_L * I_L_pred),
            dI_H_pred_t - ((1 - q) * a * S_pred - t_H * I_H_pred),
            dT_pred_t - (t_L * I_L_pred + t_H * I_H_pred - l * T_pred),
            dR_pred_t - (p * l * T_pred - r * R_pred),
            dC_pred_t - ((1 - p) * l * T_pred),
        ]

    geom = dde.geometry.TimeDomain(data_t[0, 0], data_t[-1, 0])

    y_noise = data_y + np.random.normal(loc=0, scale=data_y.std(axis=0), size=data_y.shape) * noise_level

    # Train data
    observe_S = dde.icbc.PointSetBC(data_t, y_noise[:, 0:1], component=0)
    observe_I_L = dde.icbc.PointSetBC(data_t, y_noise[:, 1:2], component=1)
    observe_I_H = dde.icbc.PointSetBC(data_t, y_noise[:, 2:3], component=2)
    observe_T = dde.icbc.PointSetBC(data_t, y_noise[:, 3:4], component=3)
    observe_R = dde.icbc.PointSetBC(data_t, y_noise[:, 4:5], component=4)
    observe_C = dde.icbc.PointSetBC(data_t, y_noise[:, 5:6], component=5)


    # Model
    data = dde.data.PDE(
        geom,
        ODE,
        [
            observe_S,
            observe_I_L,
            observe_I_H,
            observe_T,
            observe_R,
            observe_C
        ],
        num_domain=0,
        num_boundary=0,
        anchors=data_t,
    )

    net = dde.nn.FNN([1] + [64] * 3 + [6], "swish", "Glorot normal")

    def feature_transform(t):
        t = t / data_t[-1, 0]
        return t

    net.apply_feature_transform(feature_transform)

    iterations = 50000
    model = dde.Model(data, net)
    model.compile(
        "adam",
        lr=1e-3,
        loss_weights=6 * [1] + 6 * [1],
        external_trainable_variables=variable_list
    )
    variable = dde.callbacks.VariableValue(
        variable_list,
        period=5000,
        filename=variable_filename
    )
    losshistory, train_state = model.train(
        iterations=iterations,
        display_every=10000,
        callbacks=[variable]
      )
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    return model, variable

from scipy.special import expit

noise_levels = [0.01, 0.05, 0.10, 0.20]
predicted_parameters = {}
parameters_history_by_noise = {}

N = 1e6
a = 0.045
l = 0.1
p = 0.9
r = 0.01
q = 0.85
t_L = 0.2
t_H = 0.8
parameters_real = [a, l, p, r, q, t_L, t_H]

t = np.arange(0, 365, 7)[:, np.newaxis]

for noise_level in noise_levels:
    print(f"Training with noise level: {noise_level}")
    variable_filename = f"variables_{int(noise_level * 100)}percent.dat"

    trial_predictions = []
    for trial in range(n_trials):
        print(f"--- Running Trial {trial + 1}/{n_trials} ---")
        seed = int((noise_level * 1000) + trial)
        dde.config.set_random_seed(seed)
        np.random.seed(seed)
        tf.random.set_seed(seed)

        model, variable = dinn(t, y, N, noise_level, variable_filename=variable_filename)
        trial_predictions.append(expit(variable.value))
        tf.keras.backend.clear_session()

    mean_preds = np.mean(trial_predictions, axis=0)
    predicted_parameters[f"{int(noise_level * 100)}%"] = mean_preds

    parameter_names = [
      "alpha",
      "lambda",
      "p",
      "r",
      "q",
      "tau_L",
      "tau_H"
    ]

    errors = (
        pd.DataFrame(
            {
                "real": parameters_real,
                "predicted": mean_preds
            },
            index=parameter_names
        )
    )

    lines = open(variable_filename, "r").readlines()
    raw_parameters_pred_history = np.array(
      [
        np.fromstring(
          min(re.findall(re.escape("[") + "(.*?)" + re.escape("]"), line), key=len),
          sep=",",
        ) for line in lines
      ]
    )
    iterations = [int(re.findall("^[0-9]+", line)[0]) for line in lines]
    parameters_pred_history = {
      name: expit(raw_parameters_pred_history[:, i])
      for i, name in enumerate(parameter_names)
    }
    parameters_history_by_noise[f"{int(noise_level * 100)}%"] = parameters_pred_history

    n_callbacks, n_variables = raw_parameters_pred_history.shape
    fig, axes = plt.subplots(nrows=n_variables, sharex=True, figsize=(10, 8), layout="constrained")
    for ax, (parameter, parameter_value) in zip(axes, zip(parameter_names, parameters_real)):
      ax.plot(iterations, parameters_pred_history[parameter] , "-", label="Estimation")
      ax.hlines(parameter_value, xmin=0, xmax=iterations[-1], linestyles="dashed",  color=sns.color_palette()[1], label="Actual")
      ax.set_ylabel(parameter)
      ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    ax.set_xlabel("Iterations")
    fig.suptitle(f"Parameter estimation with noise level: {noise_level}")
    plt.show()

    print(
      errors.style
      .format(
        {
          "real": "{:.4f}",
          "predicted": "{:.4f}",
          "relative_error": "{:.4f}",
        }
      ).to_latex(
        label=f"tab:sirdt_errors_{int(noise_level * 100)}",
        caption=f"Parameter predictions and relative errors with noise level: {noise_level}",
      )
    )

from scipy.special import expit

parameter_names = [
    "alpha",
    "lambda",
    "p",
    "r",
    "q",
    "tau_L",
    "tau_H"
]

n_variables = len(parameter_names)

for noise_level in noise_levels:
    variable_filename = f"variables_{int(noise_level * 100)}percent.dat"
    lines = open(variable_filename, "r").readlines()
    raw_parameters_pred_history = np.array(
        [
            np.fromstring(
                min(re.findall(re.escape("[") + "(.*?)" + re.escape("]"), line), key=len),
                sep=",",
            )
            for line in lines
        ]
    )

    iterations = [int(re.findall("^[0-9]+", line)[0]) for line in lines]
    parameters_pred_history = {
        name: expit(raw_parameters_pred_history[:, j])
        for j, name in enumerate(parameter_names)
    }

    fig, axes = plt.subplots(nrows=n_variables, sharex=True, figsize=(8, 10), layout="constrained")

    for j, (parameter, parameter_value) in enumerate(zip(parameter_names, parameters_real)):
        ax = axes[j]
        ax.plot(iterations, parameters_pred_history[parameter], "-", label="Estimation")
        ax.hlines(parameter_value, xmin=0, xmax=iterations[-1], linestyles="dashed", color=sns.color_palette()[1], label="Actual")
        ax.set_ylabel(parameter)

        if j == n_variables - 1:
            ax.set_xlabel("Iterations")

    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc='center right', bbox_to_anchor=(1.2, 0.5), fancybox=True, shadow=True)

    fig.suptitle(f"Parameter Estimation History - Noise Level: {noise_level}")
    plt.show()

relative_errors_data = {
    "real": parameters_real,
    "relative error (1%)": (abs(np.array(parameters_real) - predicted_parameters["1%"]) / np.array(parameters_real)) * 100,
    "relative error (5%)": (abs(np.array(parameters_real) - predicted_parameters["5%"]) / np.array(parameters_real)) * 100,
    "relative error (10%)": (abs(np.array(parameters_real) - predicted_parameters["10%"]) / np.array(parameters_real)) * 100,
    "relative error (20%)": (abs(np.array(parameters_real) - predicted_parameters["20%"]) / np.array(parameters_real)) * 100,
}

relative_errors_df = pd.DataFrame(relative_errors_data, index=parameter_names)

print(
    relative_errors_df.style
    .format(
        {
            "real": "{:.4f}",
            "relative error (1%)": "{:.4f}",
            "relative error (5%)": "{:.4f}",
            "relative error (10%)": "{:.4f}",
            "relative error (20%)": "{:.4f}",
        }
    ).to_latex(
        label="tab:relative_errors",
        caption="Relative errors of parameter predictions with different noise levels",
    )
)

"""## Two Cohort Model"""

def twocohort_model(t, z, a_f, l_f, p_f, r_f, q_f, t_Lf, t_Hf, a_t, l_t, p_t, r_t, q_t, t_Lt, t_Ht, b_t):

    def func(y, t):
        S_f, I_Lf, I_Hf, T_f, R_f, C_f, S_t, I_Lt, I_Ht, T_t, R_t, C_t = y
        dS_f = -a_f * S_f + b_t * C_t
        dI_Lf = q_f * a_f * S_f + r_f * R_f - t_Lf * I_Lf
        dI_Hf = (1-q_f) * a_f * S_f - t_Hf * I_Hf
        dT_f = t_Lf * I_Lf + t_Hf * I_Hf - l_f * T_f
        dR_f = p_f * l_f * T_f - r_f * R_f
        dC_f = (1-p_f) * l_f * T_f
        dS_t = -a_t * S_t
        dI_Lt = q_t * a_t * S_t + r_t * R_t - t_Lt * I_Lt
        dI_Ht = (1-q_t) * a_t * S_t - t_Ht * I_Ht
        dT_t = t_Lt * I_Lt + t_Ht * I_Ht - l_t * T_t
        dR_t = p_t * l_t * T_t - r_t * R_t
        dC_t = (1-p_t) * l_t * T_t - b_t * C_t
        return [dS_f, dI_Lf, dI_Hf, dT_f, dR_f, dC_f, dS_t, dI_Lt, dI_Ht, dT_t, dR_t, dC_t]

    S_f_0 = 0.8 * N
    I_Hf_0 = 0
    I_Lf_0 = 0
    T_f_0 = 0
    R_f_0 = 0
    C_f_0 = 0
    S_t_0 = 0.2 * N
    I_Ht_0 = 0
    I_Lt_0 = 0
    T_t_0 = 0
    R_t_0 = 0
    C_t_0 = 0
    y0 = [S_f_0, I_Lf_0, I_Hf_0, T_f_0, R_f_0, C_f_0, S_t_0, I_Lt_0, I_Ht_0, T_t_0, R_t_0, C_t_0]
    return odeint(func, y0, t)

a_f = 0.045
l_f = 0.1
p_f = 0.9
r_f = 0.01
q_f = 0.85
t_Lf = 0.2
t_Hf = 0.8
a_t = 0.18
l_t = 0.41
p_t = 0.92
r_t = 0.055
q_t = 0.9
t_Lt = 0.3
t_Ht = 0.9
b_t = 0.4
N = 1e6

t = np.arange(0, 365, 7)[:, np.newaxis]

parameters_real_coh = [a_f, l_f, p_f, r_f, q_f, t_Lf, t_Hf, a_t, l_t, p_t, r_t, q_t, t_Lt, t_Ht, b_t]

z = twocohort_model(np.ravel(t), N, a_f, l_f, p_f, r_f, q_f, t_Lf, t_Hf, a_t, l_t, p_t, r_t, q_t, t_Lt, t_Ht, b_t)

def dinn_coh(data_t, data_y, N, noise_level):

    a_f = dde.Variable(0.1)
    l_f = dde.Variable(0.1)
    p_f = dde.Variable(0.1)
    r_f = dde.Variable(0.1)
    q_f = dde.Variable(0.1)
    t_Lf = dde.Variable(0.1)
    t_Hf = dde.Variable(0.1)
    a_t = dde.Variable(0.1)
    l_t = dde.Variable(0.1)
    p_t = dde.Variable(0.1)
    r_t = dde.Variable(0.1)
    q_t = dde.Variable(0.1)
    t_Lt = dde.Variable(0.1)
    t_Ht = dde.Variable(0.1)
    b_t = dde.Variable(0.1)
    variable_list = [a_f, l_f, p_f, r_f, q_f, t_Lf, t_Hf, a_t, l_t, p_t, r_t, q_t, t_Lt, t_Ht, b_t]

    def ODE(t, y_pred):
        S_f_pred = y_pred[:, 0:1]
        I_Lf_pred = y_pred[:, 1:2]
        I_Hf_pred = y_pred[:, 2:3]
        T_f_pred = y_pred[:, 3:4]
        R_f_pred = y_pred[:, 4:5]
        C_f_pred = y_pred[:, 5:6]
        S_t_pred = y_pred[:, 6:7]
        I_Lt_pred = y_pred[:, 7:8]
        I_Ht_pred = y_pred[:, 8:9]
        T_t_pred = y_pred[:, 9:10]
        R_t_pred = y_pred[:, 10:11]
        C_t_pred = y_pred[:, 11:12]

        dS_f_pred_t = dde.grad.jacobian(y_pred, t, i=0)
        dI_Lf_pred_t = dde.grad.jacobian(y_pred, t, i=1)
        dI_Hf_pred_t = dde.grad.jacobian(y_pred, t, i=2)
        dT_f_pred_t = dde.grad.jacobian(y_pred, t, i=3)
        dR_f_pred_t = dde.grad.jacobian(y_pred, t, i=4)
        dC_f_pred_t = dde.grad.jacobian(y_pred, t, i=5)
        dS_t_pred_t = dde.grad.jacobian(y_pred, t, i=6)
        dI_Lt_pred_t = dde.grad.jacobian(y_pred, t, i=7)
        dI_Ht_pred_t = dde.grad.jacobian(y_pred, t, i=8)
        dT_t_pred_t = dde.grad.jacobian(y_pred, t, i=9)
        dR_t_pred_t = dde.grad.jacobian(y_pred, t, i=10)
        dC_t_pred_t = dde.grad.jacobian(y_pred, t, i=11)

        return [
            dS_f_pred_t - (-a_f * S_f_pred + b_t * C_t_pred),
            dI_Lf_pred_t - (q_f * a_f * S_f_pred + r_f * R_f_pred - t_Lf * I_Lf_pred),
            dI_Hf_pred_t - ((1-q_f) * a_f * S_f_pred - t_Hf * I_Hf_pred),
            dT_f_pred_t - (t_Lf * I_Lf_pred + t_Hf * I_Hf_pred - l_f * T_f_pred),
            dR_f_pred_t - (p_f * l_f * T_f_pred - r_f * R_f_pred),
            dC_f_pred_t - ((1-p_f) * l_f * T_f_pred),
            dS_t_pred_t - (-a_t * S_t_pred),
            dI_Lt_pred_t - (q_t * a_t * S_t_pred + r_t * R_t_pred - t_Lt * I_Lt_pred),
            dI_Ht_pred_t - ((1-q_t) * a_t * S_t_pred - t_Ht * I_Ht_pred),
            dT_t_pred_t - (t_Lt * I_Lt_pred + t_Ht * I_Ht_pred - l_t * T_t_pred),
            dR_t_pred_t - (p_t * l_t * T_t_pred - r_t * R_t_pred),
            dC_t_pred_t - ((1-p_t) * l_t * T_t_pred - b_t * C_t_pred),
        ]

    geom = dde.geometry.TimeDomain(data_t[0, 0], data_t[-1, 0])

    y_noise = data_y + np.random.normal(loc=0, scale=data_y.std(axis=0), size=data_y.shape) * noise_level

    # Train data
    observe_S_f = dde.icbc.PointSetBC(data_t, y_noise[:, 0:1], component=0)
    observe_I_Lf = dde.icbc.PointSetBC(data_t, y_noise[:, 1:2], component=1)
    observe_I_Hf = dde.icbc.PointSetBC(data_t, y_noise[:, 2:3], component=2)
    observe_T_f = dde.icbc.PointSetBC(data_t, y_noise[:, 3:4], component=3)
    observe_R_f = dde.icbc.PointSetBC(data_t, y_noise[:, 4:5], component=4)
    observe_C_f = dde.icbc.PointSetBC(data_t, y_noise[:, 5:6], component=5)
    observe_S_t = dde.icbc.PointSetBC(data_t, y_noise[:, 6:7], component=6)
    observe_I_Lt = dde.icbc.PointSetBC(data_t, y_noise[:, 7:8], component=7)
    observe_I_Ht = dde.icbc.PointSetBC(data_t, y_noise[:, 8:9], component=8)
    observe_T_t = dde.icbc.PointSetBC(data_t, y_noise[:, 9:10], component=9)
    observe_R_t = dde.icbc.PointSetBC(data_t, y_noise[:, 10:11], component=10)
    observe_C_t = dde.icbc.PointSetBC(data_t, y_noise[:, 11:12], component=11)

    # Model
    data = dde.data.PDE(
        geom,
        ODE,
        [
            observe_S_f,
            observe_I_Lf,
            observe_I_Hf,
            observe_T_f,
            observe_R_f,
            observe_C_f,
            observe_S_t,
            observe_I_Lt,
            observe_I_Ht,
            observe_T_t,
            observe_R_t,
            observe_C_t
        ],
        num_domain=256,
        num_boundary=0,
        anchors=data_t,
    )

    net = dde.nn.FNN([1] + [64] * 3 + [12], "swish", "Glorot normal")

    def feature_transform(t):
        t = t / data_t[-1, 0]
        return dde.backend.concat(
            (
                t,
                dde.backend.sin(np.pi * t),
                dde.backend.sin(2 * np.pi * t),
            ),
            axis=1,
        )

    def output_transform(t, y):
        return N * y

    net.apply_feature_transform(feature_transform)
    net.apply_output_transform(output_transform)

    iterations = 50000
    model = dde.Model(data, net)
    model.compile(
        "adam",
        lr=1e-3,
        loss_weights=12 * [1] + 12 * [1],
        external_trainable_variables=variable_list
    )
    variable = dde.callbacks.VariableValue(
        variable_list,
        period=5000,
        filename="variables.dat"
    )
    losshistory, train_state = model.train(
        iterations=iterations,
        display_every=10000,
        callbacks=[variable]
      )
    dde.saveplot(losshistory, train_state, issave=True, isplot=True)
    return model, variable

predicted_parameters = {}
noise_levels_coh = [0.01]

for noise_level in noise_levels_coh:
    print(f"Training with noise level: {noise_level}")
    model, variable = dinn_coh(t, z, N, noise_level)
    predicted_parameters[f"{int(noise_level * 100)}%"] = variable.value

    parameter_names = [
      "alpha_f",
      "lambda_f",
      "p_f",
      "r_f",
      "q_f",
      "tau_Lf",
      "tau_Hf",
      "alpha_t",
      "lambda_t",
      "p_t",
      "r_t",
      "q_t",
      "tau_Lt",
      "tau_Ht",
      "b_t"
    ]

    errors = (
        pd.DataFrame(
            {
                "real": parameters_real_coh,
                "predicted": variable.value
            },
            index=parameter_names
        )
        .assign(
            relative_error=lambda x: (x["real"] - x["predicted"]).abs() / x["real"] * 100
        )
    )

    variable_filename = "variables.dat"

    lines = open(variable_filename, "r").readlines()
    raw_parameters_pred_history = np.array(
      [
        np.fromstring(
          min(re.findall(re.escape("[") + "(.*?)" + re.escape("]"), line), key=len),
          sep=",",
        ) for line in lines
      ]
    )
    iterations = [int(re.findall("^[0-9]+", line)[0]) for line in lines]
    parameters_pred_history = {
      name: raw_parameters_pred_history[:, i]
      for i, name in enumerate(parameter_names)
    }

    n_callbacks, n_variables = raw_parameters_pred_history.shape
    fig, axes = plt.subplots(nrows=n_variables, sharex=True, figsize=(7, 14), layout="constrained")
    for ax, (parameter, parameter_value) in zip(axes, zip(parameter_names, parameters_real_coh)):
      ax.plot(iterations, parameters_pred_history[parameter] , "-", label="Estimation")
      ax.hlines(parameter_value, xmin=0, xmax=iterations[-1], linestyles="dashed",  color=sns.color_palette()[1], label="Actual")
      ax.set_ylabel(parameter)
      ax.legend()
    ax.set_xlabel("Iterations")
    fig.suptitle(f"Parameter estimation with noise level: {noise_level}")
    plt.show()

    print(
      errors.style
      .format(
        {
          "real": "{:.4f}",
          "predicted": "{:.4f}",
          "relative_error": "{:.4f}",
        }
      ).to_latex(
        label=f"tab:sirdt_errors_{int(noise_level * 100)}",
        caption=f"Parameter predictions and relative errors with noise level: {noise_level}",
      )
    )
